// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"
	"time"
)

type FakeStatsdClientPrototype struct {
	IncrStub        func(name string, tags []string, rate float64) error
	incrMutex       sync.RWMutex
	incrArgsForCall []struct {
		name string
		tags []string
		rate float64
	}
	incrReturns struct {
		result1 error
	}
	incrReturnsOnCall map[int]struct {
		result1 error
	}
	TimingStub        func(name string, value time.Duration, tags []string, rate float64) error
	timingMutex       sync.RWMutex
	timingArgsForCall []struct {
		name  string
		value time.Duration
		tags  []string
		rate  float64
	}
	timingReturns struct {
		result1 error
	}
	timingReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeStatsdClientPrototype) Incr(name string, tags []string, rate float64) error {
	var tagsCopy []string
	if tags != nil {
		tagsCopy = make([]string, len(tags))
		copy(tagsCopy, tags)
	}
	fake.incrMutex.Lock()
	ret, specificReturn := fake.incrReturnsOnCall[len(fake.incrArgsForCall)]
	fake.incrArgsForCall = append(fake.incrArgsForCall, struct {
		name string
		tags []string
		rate float64
	}{name, tagsCopy, rate})
	fake.recordInvocation("Incr", []interface{}{name, tagsCopy, rate})
	fake.incrMutex.Unlock()
	if fake.IncrStub != nil {
		return fake.IncrStub(name, tags, rate)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.incrReturns.result1
}

func (fake *FakeStatsdClientPrototype) IncrCallCount() int {
	fake.incrMutex.RLock()
	defer fake.incrMutex.RUnlock()
	return len(fake.incrArgsForCall)
}

func (fake *FakeStatsdClientPrototype) IncrArgsForCall(i int) (string, []string, float64) {
	fake.incrMutex.RLock()
	defer fake.incrMutex.RUnlock()
	return fake.incrArgsForCall[i].name, fake.incrArgsForCall[i].tags, fake.incrArgsForCall[i].rate
}

func (fake *FakeStatsdClientPrototype) IncrReturns(result1 error) {
	fake.IncrStub = nil
	fake.incrReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStatsdClientPrototype) IncrReturnsOnCall(i int, result1 error) {
	fake.IncrStub = nil
	if fake.incrReturnsOnCall == nil {
		fake.incrReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.incrReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStatsdClientPrototype) Timing(name string, value time.Duration, tags []string, rate float64) error {
	var tagsCopy []string
	if tags != nil {
		tagsCopy = make([]string, len(tags))
		copy(tagsCopy, tags)
	}
	fake.timingMutex.Lock()
	ret, specificReturn := fake.timingReturnsOnCall[len(fake.timingArgsForCall)]
	fake.timingArgsForCall = append(fake.timingArgsForCall, struct {
		name  string
		value time.Duration
		tags  []string
		rate  float64
	}{name, value, tagsCopy, rate})
	fake.recordInvocation("Timing", []interface{}{name, value, tagsCopy, rate})
	fake.timingMutex.Unlock()
	if fake.TimingStub != nil {
		return fake.TimingStub(name, value, tags, rate)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.timingReturns.result1
}

func (fake *FakeStatsdClientPrototype) TimingCallCount() int {
	fake.timingMutex.RLock()
	defer fake.timingMutex.RUnlock()
	return len(fake.timingArgsForCall)
}

func (fake *FakeStatsdClientPrototype) TimingArgsForCall(i int) (string, time.Duration, []string, float64) {
	fake.timingMutex.RLock()
	defer fake.timingMutex.RUnlock()
	return fake.timingArgsForCall[i].name, fake.timingArgsForCall[i].value, fake.timingArgsForCall[i].tags, fake.timingArgsForCall[i].rate
}

func (fake *FakeStatsdClientPrototype) TimingReturns(result1 error) {
	fake.TimingStub = nil
	fake.timingReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeStatsdClientPrototype) TimingReturnsOnCall(i int, result1 error) {
	fake.TimingStub = nil
	if fake.timingReturnsOnCall == nil {
		fake.timingReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.timingReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeStatsdClientPrototype) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.incrMutex.RLock()
	defer fake.incrMutex.RUnlock()
	fake.timingMutex.RLock()
	defer fake.timingMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeStatsdClientPrototype) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
